// var canvas = document.createElement('canvas');
// document.body.appendChild(canvas);
// var processing = new Processing(canvas, 
// // this code was autogenerated from PJS
// (function($p) {

// 	function setup() {
// 		$p.size(800, 500);
// 	    $p.frameRate(20);
// 	    $p.strokeWeight(12);
// 	}
// 	$p.setup = setup;
// 	var variable_16 =  0;
// 	function draw() {
// 		$p.stroke($p.color($p.color($p.random(0, 255), $p.random(0, 255), $p.random(0, 255), $p.random(0, 255))));
// 	    $p.line(0, 0, $p.random(0, $p.width), $p.random(0, $p.height));
// 	    if ((variable_16 < $p.width)) {
// 			variable_16 += 1;
// 		} else {
// 			variable_16 = 0;
// 		}
// 	}
// 	$p.draw = draw;
// })
// );

var script = new Function([	
	'var canvas = document.createElement("canvas");',
	'document.body.appendChild(canvas);',
	'var processing = new Processing(canvas,',
	'// this code was autogenerated from PJS',
	'(function($p) {',
    '',
	'function setup() {',
	'$p.size(800, 500);',
	'    $p.frameRate(20);',
	'    $p.strokeWeight(12);',
	'}',
	'$p.setup = setup;',
	'var variable_16 =  0;',
	'function draw() {',
	'$p.stroke($p.color($p.color($p.random(0, 255), $p.random(0, 255), $p.random(0, 255), $p.random(0, 255))));',
	'    $p.line(0, 0, $p.random(0, $p.width), $p.random(0, $p.height));',
	'    if ((variable_16 < $p.width)) {',
	'variable_16 += 1;',
	'} else {',
	'variable_16 = 0;',
	'}',
	'}',
	'$p.draw = draw;',
	'})',
	');'
].join('\n'))();